// Generated by ChatGPT.
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>

typedef float f32;

typedef struct {
    f32 x;
    f32 y;
    f32 radius;
    f32 theta;
    f32 strength;
    f32 t;
    f32 interval;
} Wind_Force;

static int print_json(const char *filename)
{
    FILE *fp = fopen(filename, "rb");
    if (!fp) {
        perror("fopen");
        return 1;
    }

    size_t count;

    if (fread(&count, sizeof(count), 1, fp) != 1) {
        fprintf(stderr, "Failed to read count\n");
        fclose(fp);
        return 1;
    }

    printf("{\n");
    printf("  \"count\": %zu,\n", count);
    printf("  \"wind_forces\": [\n");

    for (size_t i = 0; i < count; ++i) {
        Wind_Force w;

        if (fread(&w, sizeof(w), 1, fp) != 1) {
            fprintf(stderr, "Failed to read element %zu\n", i);
            fclose(fp);
            return 1;
        }

        printf("    {\n");
        printf("      \"x\": %.9g,\n", w.x);
        printf("      \"y\": %.9g,\n", w.y);
        printf("      \"radius\": %.9g,\n", w.radius);
        printf("      \"theta\": %.9g,\n", w.theta);
        printf("      \"strength\": %.9g,\n", w.strength);
        printf("      \"t\": %.9g,\n", w.t);
        printf("      \"interval\": %.9g\n", w.interval);

        printf(i + 1 < count ? "    },\n" : "    }\n");
    }

    printf("  ]\n");
    printf("}\n");

    fclose(fp);
    return 0;
}

static int edit_field(
    const char *filename,
    size_t index,
    const char *field,
    float value)
{
    FILE *fp = fopen(filename, "r+b");
    if (!fp) {
        perror("fopen");
        return 1;
    }

    size_t count;

    if (fread(&count, sizeof(count), 1, fp) != 1) {
        fprintf(stderr, "Failed to read count\n");
        fclose(fp);
        return 1;
    }

    if (index >= count) {
        fprintf(stderr, "Index %zu out of range [0,%zu)\n",
                index, count);
        fclose(fp);
        return 1;
    }

    long field_offset = -1;

#define FIELD(name) \
    if (strcmp(field, #name) == 0) \
        field_offset = offsetof(Wind_Force, name)

    FIELD(x);
    else FIELD(y);
    else FIELD(radius);
    else FIELD(theta);
    else FIELD(strength);
    else FIELD(t);
    else FIELD(interval);

#undef FIELD

    if (field_offset < 0) {
        fprintf(stderr,
                "Unknown field '%s'\n"
                "Valid fields: "
                "x y radius theta strength t interval\n",
                field);
        fclose(fp);
        return 1;
    }

    long pos =
        (long)sizeof(size_t) +
        (long)(index * sizeof(Wind_Force)) +
        field_offset;

    if (fseek(fp, pos, SEEK_SET) != 0) {
        perror("fseek");
        fclose(fp);
        return 1;
    }

    f32 v = value;

    if (fwrite(&v, sizeof(v), 1, fp) != 1) {
        fprintf(stderr, "Write failed\n");
        fclose(fp);
        return 1;
    }

    fclose(fp);

    printf(
        "Updated record %zu field '%s' -> %g\n",
        index,
        field,
        value);

    return 0;
}

static void usage(const char *prog)
{
    fprintf(stderr,
        "Usage:\n"
        "  %s view <file>\n"
        "  %s edit <file> <index> <field> <value>\n",
        prog,
        prog);
}

int main(int argc, char **argv)
{
    if (argc >= 3 && strcmp(argv[1], "view") == 0) {
        return print_json(argv[2]);
    }

    if (argc == 6 && strcmp(argv[1], "edit") == 0) {
        size_t index = strtoull(argv[3], NULL, 10);
        float value = strtof(argv[5], NULL);

        return edit_field(
            argv[2],
            index,
            argv[4],
            value);
    }

    usage(argv[0]);
    return 1;
}
